# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.models.git_deployment_metadata_provider import GitDeploymentMetadataProvider


class TestGitDeploymentMetadataProvider(unittest.TestCase):
    """GitDeploymentMetadataProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGitDeploymentMetadataProvider(self):
        """Test GitDeploymentMetadataProvider"""
        # inst = GitDeploymentMetadataProvider()


if __name__ == "__main__":
    unittest.main()
