# coding: utf-8

# flake8: noqa
"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from koyeb.models.accept_organization_invitation_reply import (
    AcceptOrganizationInvitationReply,
)
from koyeb.models.action import Action
from koyeb.models.activity import Activity
from koyeb.models.activity_list import ActivityList
from koyeb.models.app import App
from koyeb.models.app_event import AppEvent
from koyeb.models.app_list_item import AppListItem
from koyeb.models.app_status import AppStatus
from koyeb.models.app_usage import AppUsage
from koyeb.models.apps_summary import AppsSummary
from koyeb.models.archive import Archive
from koyeb.models.archive_deployment_metadata import ArchiveDeploymentMetadata
from koyeb.models.archive_source import ArchiveSource
from koyeb.models.auto_release import AutoRelease
from koyeb.models.auto_release_group import AutoReleaseGroup
from koyeb.models.autocomplete_reply import AutocompleteReply
from koyeb.models.autocomplete_request import AutocompleteRequest
from koyeb.models.availability_level import AvailabilityLevel
from koyeb.models.azure_container_registry_configuration import (
    AzureContainerRegistryConfiguration,
)
from koyeb.models.budget import Budget
from koyeb.models.buildpack_builder import BuildpackBuilder
from koyeb.models.canny_auth_reply import CannyAuthReply
from koyeb.models.catalog_gpu_details import CatalogGPUDetails
from koyeb.models.catalog_instance import CatalogInstance
from koyeb.models.catalog_instance_list_item import CatalogInstanceListItem
from koyeb.models.catalog_usage import CatalogUsage
from koyeb.models.compose_reply import ComposeReply
from koyeb.models.config_file import ConfigFile
from koyeb.models.confirm_payment_authorization_reply import (
    ConfirmPaymentAuthorizationReply,
)
from koyeb.models.create_account_request import CreateAccountRequest
from koyeb.models.create_app import CreateApp
from koyeb.models.create_app_reply import CreateAppReply
from koyeb.models.create_archive import CreateArchive
from koyeb.models.create_archive_reply import CreateArchiveReply
from koyeb.models.create_budget_reply import CreateBudgetReply
from koyeb.models.create_compose import CreateCompose
from koyeb.models.create_credential import CreateCredential
from koyeb.models.create_credential_reply import CreateCredentialReply
from koyeb.models.create_domain import CreateDomain
from koyeb.models.create_domain_reply import CreateDomainReply
from koyeb.models.create_organization_invitation_reply import (
    CreateOrganizationInvitationReply,
)
from koyeb.models.create_organization_invitation_request import (
    CreateOrganizationInvitationRequest,
)
from koyeb.models.create_organization_reply import CreateOrganizationReply
from koyeb.models.create_organization_request import CreateOrganizationRequest
from koyeb.models.create_payment_authorization_reply import (
    CreatePaymentAuthorizationReply,
)
from koyeb.models.create_persistent_volume_reply import CreatePersistentVolumeReply
from koyeb.models.create_persistent_volume_request import CreatePersistentVolumeRequest
from koyeb.models.create_secret import CreateSecret
from koyeb.models.create_secret_reply import CreateSecretReply
from koyeb.models.create_service import CreateService
from koyeb.models.create_service_reply import CreateServiceReply
from koyeb.models.create_snapshot_reply import CreateSnapshotReply
from koyeb.models.create_snapshot_request import CreateSnapshotRequest
from koyeb.models.create_stage_attempt_request import CreateStageAttemptRequest
from koyeb.models.credential import Credential
from koyeb.models.credential_type import CredentialType
from koyeb.models.database_deployment_metadata import DatabaseDeploymentMetadata
from koyeb.models.database_role_password import DatabaseRolePassword
from koyeb.models.database_source import DatabaseSource
from koyeb.models.datacenter_list_item import DatacenterListItem
from koyeb.models.deactivate_organization_reply import DeactivateOrganizationReply
from koyeb.models.deactivate_organization_request import DeactivateOrganizationRequest
from koyeb.models.declare_stage_progress_request import DeclareStageProgressRequest
from koyeb.models.declare_step_progress_request import DeclareStepProgressRequest
from koyeb.models.decline_organization_invitation_reply import (
    DeclineOrganizationInvitationReply,
)
from koyeb.models.delete_organization_reply import DeleteOrganizationReply
from koyeb.models.delete_persistent_volume_reply import DeletePersistentVolumeReply
from koyeb.models.delete_snapshot_reply import DeleteSnapshotReply
from koyeb.models.delete_user_reply import DeleteUserReply
from koyeb.models.deployment import Deployment
from koyeb.models.deployment_database_info import DeploymentDatabaseInfo
from koyeb.models.deployment_definition import DeploymentDefinition
from koyeb.models.deployment_definition_type import DeploymentDefinitionType
from koyeb.models.deployment_env import DeploymentEnv
from koyeb.models.deployment_event import DeploymentEvent
from koyeb.models.deployment_health_check import DeploymentHealthCheck
from koyeb.models.deployment_instance_type import DeploymentInstanceType
from koyeb.models.deployment_list_item import DeploymentListItem
from koyeb.models.deployment_metadata import DeploymentMetadata
from koyeb.models.deployment_neon_postgres_database_info import (
    DeploymentNeonPostgresDatabaseInfo,
)
from koyeb.models.deployment_neon_postgres_database_info_role import (
    DeploymentNeonPostgresDatabaseInfoRole,
)
from koyeb.models.deployment_port import DeploymentPort
from koyeb.models.deployment_provisioning_info import DeploymentProvisioningInfo
from koyeb.models.deployment_provisioning_info_stage import (
    DeploymentProvisioningInfoStage,
)
from koyeb.models.deployment_provisioning_info_stage_build_attempt import (
    DeploymentProvisioningInfoStageBuildAttempt,
)
from koyeb.models.deployment_provisioning_info_stage_build_attempt_build_step import (
    DeploymentProvisioningInfoStageBuildAttemptBuildStep,
)
from koyeb.models.deployment_provisioning_info_stage_status import (
    DeploymentProvisioningInfoStageStatus,
)
from koyeb.models.deployment_role import DeploymentRole
from koyeb.models.deployment_route import DeploymentRoute
from koyeb.models.deployment_scaling import DeploymentScaling
from koyeb.models.deployment_scaling_target import DeploymentScalingTarget
from koyeb.models.deployment_scaling_target_average_cpu import (
    DeploymentScalingTargetAverageCPU,
)
from koyeb.models.deployment_scaling_target_average_mem import (
    DeploymentScalingTargetAverageMem,
)
from koyeb.models.deployment_scaling_target_concurrent_requests import (
    DeploymentScalingTargetConcurrentRequests,
)
from koyeb.models.deployment_scaling_target_requests_per_second import (
    DeploymentScalingTargetRequestsPerSecond,
)
from koyeb.models.deployment_scaling_target_requests_response_time import (
    DeploymentScalingTargetRequestsResponseTime,
)
from koyeb.models.deployment_scaling_target_sleep_idle_delay import (
    DeploymentScalingTargetSleepIdleDelay,
)
from koyeb.models.deployment_status import DeploymentStatus
from koyeb.models.deployment_strategy import DeploymentStrategy
from koyeb.models.deployment_strategy_type import DeploymentStrategyType
from koyeb.models.deployment_volume import DeploymentVolume
from koyeb.models.desired_deployment import DesiredDeployment
from koyeb.models.desired_deployment_group import DesiredDeploymentGroup
from koyeb.models.digital_ocean_registry_configuration import (
    DigitalOceanRegistryConfiguration,
)
from koyeb.models.discourse_auth_reply import DiscourseAuthReply
from koyeb.models.discourse_auth_request import DiscourseAuthRequest
from koyeb.models.docker_builder import DockerBuilder
from koyeb.models.docker_hub_registry_configuration import (
    DockerHubRegistryConfiguration,
)
from koyeb.models.docker_source import DockerSource
from koyeb.models.domain import Domain
from koyeb.models.domain_load_balancer_koyeb import DomainLoadBalancerKoyeb
from koyeb.models.domain_load_balancer_quotas import DomainLoadBalancerQuotas
from koyeb.models.domain_status import DomainStatus
from koyeb.models.domain_type import DomainType
from koyeb.models.domains_summary import DomainsSummary
from koyeb.models.env import Env
from koyeb.models.error import Error
from koyeb.models.error_field import ErrorField
from koyeb.models.error_with_fields import ErrorWithFields
from koyeb.models.exec_command_io import ExecCommandIO
from koyeb.models.exec_command_reply import ExecCommandReply
from koyeb.models.exec_command_request_body import ExecCommandRequestBody
from koyeb.models.exec_command_request_id_type import ExecCommandRequestIdType
from koyeb.models.exec_command_request_terminal_size import (
    ExecCommandRequestTerminalSize,
)
from koyeb.models.gcp_container_registry_configuration import (
    GCPContainerRegistryConfiguration,
)
from koyeb.models.get_app_reply import GetAppReply
from koyeb.models.get_budget_reply import GetBudgetReply
from koyeb.models.get_catalog_instance_reply import GetCatalogInstanceReply
from koyeb.models.get_credential_reply import GetCredentialReply
from koyeb.models.get_deployment_reply import GetDeploymentReply
from koyeb.models.get_deployment_scaling_reply import GetDeploymentScalingReply
from koyeb.models.get_deployment_scaling_reply_item import GetDeploymentScalingReplyItem
from koyeb.models.get_domain_reply import GetDomainReply
from koyeb.models.get_github_installation_reply import GetGithubInstallationReply
from koyeb.models.get_instance_reply import GetInstanceReply
from koyeb.models.get_intercom_profile_reply import GetIntercomProfileReply
from koyeb.models.get_metrics_reply import GetMetricsReply
from koyeb.models.get_metrics_reply_metric import GetMetricsReplyMetric
from koyeb.models.get_o_auth_options_reply import GetOAuthOptionsReply
from koyeb.models.get_organization_invitation_reply import (
    GetOrganizationInvitationReply,
)
from koyeb.models.get_organization_reply import GetOrganizationReply
from koyeb.models.get_organization_summary_reply import GetOrganizationSummaryReply
from koyeb.models.get_organization_usage_details_reply import (
    GetOrganizationUsageDetailsReply,
)
from koyeb.models.get_organization_usage_reply import GetOrganizationUsageReply
from koyeb.models.get_payment_method_reply import GetPaymentMethodReply
from koyeb.models.get_persistent_volume_reply import GetPersistentVolumeReply
from koyeb.models.get_quotas_reply import GetQuotasReply
from koyeb.models.get_region_reply import GetRegionReply
from koyeb.models.get_regional_deployment_reply import GetRegionalDeploymentReply
from koyeb.models.get_secret_reply import GetSecretReply
from koyeb.models.get_service_reply import GetServiceReply
from koyeb.models.get_snapshot_reply import GetSnapshotReply
from koyeb.models.get_subscription_reply import GetSubscriptionReply
from koyeb.models.get_user_organization_invitation_reply import (
    GetUserOrganizationInvitationReply,
)
from koyeb.models.git_deployment_metadata import GitDeploymentMetadata
from koyeb.models.git_hub_registry_configuration import GitHubRegistryConfiguration
from koyeb.models.git_lab_registry_configuration import GitLabRegistryConfiguration
from koyeb.models.git_source import GitSource
from koyeb.models.github_installation_reply import GithubInstallationReply
from koyeb.models.github_installation_request import GithubInstallationRequest
from koyeb.models.google_protobuf_any import GoogleProtobufAny
from koyeb.models.google_protobuf_null_value import GoogleProtobufNullValue
from koyeb.models.google_rpc_status import GoogleRpcStatus
from koyeb.models.http_header import HTTPHeader
from koyeb.models.http_health_check import HTTPHealthCheck
from koyeb.models.has_unpaid_invoices_reply import HasUnpaidInvoicesReply
from koyeb.models.instance import Instance
from koyeb.models.instance_availability import InstanceAvailability
from koyeb.models.instance_event import InstanceEvent
from koyeb.models.instance_list_item import InstanceListItem
from koyeb.models.instance_status import InstanceStatus
from koyeb.models.instance_usage import InstanceUsage
from koyeb.models.instances_summary import InstancesSummary
from koyeb.models.invite_user_request import InviteUserRequest
from koyeb.models.kgitproxy_branch import KgitproxyBranch
from koyeb.models.kgitproxy_git_hub_repository import KgitproxyGitHubRepository
from koyeb.models.kgitproxy_github_installation_status import (
    KgitproxyGithubInstallationStatus,
)
from koyeb.models.kgitproxy_indexing_status import KgitproxyIndexingStatus
from koyeb.models.kgitproxy_list_branches_reply import KgitproxyListBranchesReply
from koyeb.models.kgitproxy_list_repositories_reply import (
    KgitproxyListRepositoriesReply,
)
from koyeb.models.kgitproxy_repository import KgitproxyRepository
from koyeb.models.kgitproxy_repository_provider import KgitproxyRepositoryProvider
from koyeb.models.ksearch_app import KsearchApp
from koyeb.models.ksearch_global_deployment import KsearchGlobalDeployment
from koyeb.models.ksearch_instance import KsearchInstance
from koyeb.models.ksearch_organization import KsearchOrganization
from koyeb.models.ksearch_regional_deployment import KsearchRegionalDeployment
from koyeb.models.ksearch_search_reply import KsearchSearchReply
from koyeb.models.ksearch_service import KsearchService
from koyeb.models.ksearch_user import KsearchUser
from koyeb.models.list_app_events_reply import ListAppEventsReply
from koyeb.models.list_apps_reply import ListAppsReply
from koyeb.models.list_catalog_instances_reply import ListCatalogInstancesReply
from koyeb.models.list_credentials_reply import ListCredentialsReply
from koyeb.models.list_datacenters_reply import ListDatacentersReply
from koyeb.models.list_deployment_events_reply import ListDeploymentEventsReply
from koyeb.models.list_deployments_reply import ListDeploymentsReply
from koyeb.models.list_domains_reply import ListDomainsReply
from koyeb.models.list_instance_events_reply import ListInstanceEventsReply
from koyeb.models.list_instances_reply import ListInstancesReply
from koyeb.models.list_organization_invitations_reply import (
    ListOrganizationInvitationsReply,
)
from koyeb.models.list_organization_members_reply import ListOrganizationMembersReply
from koyeb.models.list_payment_methods_reply import ListPaymentMethodsReply
from koyeb.models.list_persistent_volume_events_reply import (
    ListPersistentVolumeEventsReply,
)
from koyeb.models.list_persistent_volumes_reply import ListPersistentVolumesReply
from koyeb.models.list_regional_deployment_events_reply import (
    ListRegionalDeploymentEventsReply,
)
from koyeb.models.list_regional_deployments_reply import ListRegionalDeploymentsReply
from koyeb.models.list_regions_reply import ListRegionsReply
from koyeb.models.list_secrets_reply import ListSecretsReply
from koyeb.models.list_service_events_reply import ListServiceEventsReply
from koyeb.models.list_services_reply import ListServicesReply
from koyeb.models.list_snapshots_reply import ListSnapshotsReply
from koyeb.models.list_usage_reply import ListUsageReply
from koyeb.models.list_user_organization_invitations_reply import (
    ListUserOrganizationInvitationsReply,
)
from koyeb.models.list_user_organizations_reply import ListUserOrganizationsReply
from koyeb.models.log_entry import LogEntry
from koyeb.models.login_reply import LoginReply
from koyeb.models.login_request import LoginRequest
from koyeb.models.manage_reply import ManageReply
from koyeb.models.members_summary import MembersSummary
from koyeb.models.metric_name import MetricName
from koyeb.models.neon_postgres_database import NeonPostgresDatabase
from koyeb.models.neon_postgres_database_deployment_metadata import (
    NeonPostgresDatabaseDeploymentMetadata,
)
from koyeb.models.neon_postgres_database_neon_database import (
    NeonPostgresDatabaseNeonDatabase,
)
from koyeb.models.neon_postgres_database_neon_role import NeonPostgresDatabaseNeonRole
from koyeb.models.neon_postgres_summary import NeonPostgresSummary
from koyeb.models.next_invoice_reply import NextInvoiceReply
from koyeb.models.next_invoice_reply_discount import NextInvoiceReplyDiscount
from koyeb.models.next_invoice_reply_discount_type import NextInvoiceReplyDiscountType
from koyeb.models.next_invoice_reply_line import NextInvoiceReplyLine
from koyeb.models.next_invoice_reply_line_period import NextInvoiceReplyLinePeriod
from koyeb.models.next_invoice_reply_line_price import NextInvoiceReplyLinePrice
from koyeb.models.notification import Notification
from koyeb.models.notification_list import NotificationList
from koyeb.models.o_auth_callback_reply import OAuthCallbackReply
from koyeb.models.o_auth_callback_request import OAuthCallbackRequest
from koyeb.models.o_auth_provider import OAuthProvider
from koyeb.models.object import Object
from koyeb.models.organization import Organization
from koyeb.models.organization_deactivation_reason import OrganizationDeactivationReason
from koyeb.models.organization_detailed_status import OrganizationDetailedStatus
from koyeb.models.organization_invitation import OrganizationInvitation
from koyeb.models.organization_invitation_status import OrganizationInvitationStatus
from koyeb.models.organization_member import OrganizationMember
from koyeb.models.organization_member_status import OrganizationMemberStatus
from koyeb.models.organization_status import OrganizationStatus
from koyeb.models.organization_summary import OrganizationSummary
from koyeb.models.payment_method import PaymentMethod
from koyeb.models.payment_method_status import PaymentMethodStatus
from koyeb.models.period_usage import PeriodUsage
from koyeb.models.persistent_volume import PersistentVolume
from koyeb.models.persistent_volume_backing_store import PersistentVolumeBackingStore
from koyeb.models.persistent_volume_event import PersistentVolumeEvent
from koyeb.models.persistent_volume_quotas import PersistentVolumeQuotas
from koyeb.models.persistent_volume_status import PersistentVolumeStatus
from koyeb.models.plan import Plan
from koyeb.models.port import Port
from koyeb.models.private_registry_configuration import PrivateRegistryConfiguration
from koyeb.models.public_organization import PublicOrganization
from koyeb.models.public_user import PublicUser
from koyeb.models.query_logs_reply import QueryLogsReply
from koyeb.models.query_logs_reply_pagination import QueryLogsReplyPagination
from koyeb.models.quotas import Quotas
from koyeb.models.reactivate_organization_reply import ReactivateOrganizationReply
from koyeb.models.redeem_coupon_request import RedeemCouponRequest
from koyeb.models.redeploy_reply import RedeployReply
from koyeb.models.redeploy_request_info import RedeployRequestInfo
from koyeb.models.region import Region
from koyeb.models.region_availability import RegionAvailability
from koyeb.models.region_list_item import RegionListItem
from koyeb.models.region_usage import RegionUsage
from koyeb.models.regional_deployment import RegionalDeployment
from koyeb.models.regional_deployment_definition import RegionalDeploymentDefinition
from koyeb.models.regional_deployment_definition_type import (
    RegionalDeploymentDefinitionType,
)
from koyeb.models.regional_deployment_event import RegionalDeploymentEvent
from koyeb.models.regional_deployment_list_item import RegionalDeploymentListItem
from koyeb.models.regional_deployment_role import RegionalDeploymentRole
from koyeb.models.regional_deployment_status import RegionalDeploymentStatus
from koyeb.models.regional_deployment_volume import RegionalDeploymentVolume
from koyeb.models.remove_organization_member_reply import RemoveOrganizationMemberReply
from koyeb.models.resend_organization_invitation_reply import (
    ResendOrganizationInvitationReply,
)
from koyeb.models.reset_password_request import ResetPasswordRequest
from koyeb.models.reveal_secret_reply import RevealSecretReply
from koyeb.models.review_organization_capacity_reply import (
    ReviewOrganizationCapacityReply,
)
from koyeb.models.review_organization_capacity_request import (
    ReviewOrganizationCapacityRequest,
)
from koyeb.models.route import Route
from koyeb.models.sample import Sample
from koyeb.models.scaling import Scaling
from koyeb.models.secret import Secret
from koyeb.models.secret_type import SecretType
from koyeb.models.secrets_summary import SecretsSummary
from koyeb.models.service import Service
from koyeb.models.service_event import ServiceEvent
from koyeb.models.service_list_item import ServiceListItem
from koyeb.models.service_state import ServiceState
from koyeb.models.service_status import ServiceStatus
from koyeb.models.service_summary import ServiceSummary
from koyeb.models.service_type import ServiceType
from koyeb.models.service_usage import ServiceUsage
from koyeb.models.snapshot import Snapshot
from koyeb.models.snapshot_status import SnapshotStatus
from koyeb.models.snapshot_type import SnapshotType
from koyeb.models.stream_result_of_exec_command_reply import (
    StreamResultOfExecCommandReply,
)
from koyeb.models.stream_result_of_log_entry import StreamResultOfLogEntry
from koyeb.models.subscription import Subscription
from koyeb.models.subscription_payment_failure import SubscriptionPaymentFailure
from koyeb.models.subscription_payment_failure_stripe_sdk import (
    SubscriptionPaymentFailureStripeSDK,
)
from koyeb.models.subscription_status import SubscriptionStatus
from koyeb.models.tcp_health_check import TCPHealthCheck
from koyeb.models.token import Token
from koyeb.models.trigger_deployment_metadata import TriggerDeploymentMetadata
from koyeb.models.trigger_deployment_metadata_actor_type import (
    TriggerDeploymentMetadataActorType,
)
from koyeb.models.trigger_deployment_metadata_trigger_type import (
    TriggerDeploymentMetadataTriggerType,
)
from koyeb.models.trigger_git_deployment_metadata import TriggerGitDeploymentMetadata
from koyeb.models.trigger_git_deployment_metadata_provider import (
    TriggerGitDeploymentMetadataProvider,
)
from koyeb.models.update_app import UpdateApp
from koyeb.models.update_app_reply import UpdateAppReply
from koyeb.models.update_budget_reply import UpdateBudgetReply
from koyeb.models.update_budget_request import UpdateBudgetRequest
from koyeb.models.update_credential_reply import UpdateCredentialReply
from koyeb.models.update_domain import UpdateDomain
from koyeb.models.update_domain_reply import UpdateDomainReply
from koyeb.models.update_organization_plan_reply import UpdateOrganizationPlanReply
from koyeb.models.update_organization_plan_request import UpdateOrganizationPlanRequest
from koyeb.models.update_organization_reply import UpdateOrganizationReply
from koyeb.models.update_password_request import UpdatePasswordRequest
from koyeb.models.update_persistent_volume_reply import UpdatePersistentVolumeReply
from koyeb.models.update_persistent_volume_request import UpdatePersistentVolumeRequest
from koyeb.models.update_secret_reply import UpdateSecretReply
from koyeb.models.update_service import UpdateService
from koyeb.models.update_service_reply import UpdateServiceReply
from koyeb.models.update_snapshot_reply import UpdateSnapshotReply
from koyeb.models.update_snapshot_request import UpdateSnapshotRequest
from koyeb.models.update_user_request_user_update_body import (
    UpdateUserRequestUserUpdateBody,
)
from koyeb.models.upsert_signup_qualification_reply import (
    UpsertSignupQualificationReply,
)
from koyeb.models.upsert_signup_qualification_request import (
    UpsertSignupQualificationRequest,
)
from koyeb.models.usage import Usage
from koyeb.models.usage_details import UsageDetails
from koyeb.models.user import User
from koyeb.models.user_flags import UserFlags
from koyeb.models.user_reply import UserReply
from koyeb.models.user_role_role import UserRoleRole
from koyeb.models.verify_docker_image_reply import VerifyDockerImageReply
from koyeb.models.verify_docker_image_reply_err_code import (
    VerifyDockerImageReplyErrCode,
)
