[tool.bumpver]
current_version = "2025.7.0"
version_pattern = "YYYY.MM.PATCH[PYTAGNUM]"
commit = false
tag = false
push = false

[tool.bumpver.file_patterns]
"Makefile" = [
    "PACKAGE_VERSION?={version}",
]

