[tool.bumpver]
current_version = "2023.11.2"
version_pattern = "YYYY.MM.PATCH[PYTAGNUM]"
commit_message = "bump generated package version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = false
push = false

[tool.bumpver.file_patterns]
"Makefile" = [
    "PACKAGE_VERSION?={version}",
]

